config/routes.rb
Rails.application.routes.draw do
  resources :switches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/switch.rb
class Switch < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/switches_controller.rb
class SwitchesController < ApplicationController
  before_action :set_switch, only: [:show, :edit, :update, :destroy]

  # GET /switches
  # GET /switches.json
  def index
    @switches = Switch.all
  end

  # GET /switches/1
  # GET /switches/1.json
  def show
  end

  # GET /switches/new
  def new
    @switch = Switch.new
  end

  # GET /switches/1/edit
  def edit
  end

  # POST /switches
  # POST /switches.json
  def create
    @switch = Switch.new(switch_params)

    respond_to do |format|
      if @switch.save
        format.html { redirect_to @switch, notice: 'Switch was successfully created.' }
        format.json { render :show, status: :created, location: @switch }
      else
        format.html { render :new }
        format.json { render json: @switch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /switches/1
  # PATCH/PUT /switches/1.json
  def update
    respond_to do |format|
      if @switch.update(switch_params)
        format.html { redirect_to @switch, notice: 'Switch was successfully updated.' }
        format.json { render :show, status: :ok, location: @switch }
      else
        format.html { render :edit }
        format.json { render json: @switch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /switches/1
  # DELETE /switches/1.json
  def destroy
    @switch.destroy
    respond_to do |format|
      format.html { redirect_to switches_url, notice: 'Switch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_switch
      @switch = Switch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def switch_params
      params.require(:switch).permit(:name, :local_ip, :user, :pass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/switches_helper.rb
module SwitchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Networks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/switches/_form.html.erb
<%= form_for(switch) do |f| %>
  <% if switch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(switch.errors.count, "error") %> prohibited this switch from being saved:</h2>

      <ul>
      <% switch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :local_ip %>
    <%= f.text_field :local_ip %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div class="field">
    <%= f.label :pass %>
    <%= f.text_field :pass %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/switches/edit.html.erb
<h1>Editing Switch</h1>

<%= render 'form', switch: @switch %>

<%= link_to 'Show', @switch %> |
<%= link_to 'Back', switches_path %>

app/views/switches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Switches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Local ip</th>
      <th>User</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @switches.each do |switch| %>
      <tr>
        <td><%= switch.name %></td>
        <td><%= switch.local_ip %></td>
        <td><%= switch.user %></td>
        <td><%= switch.pass %></td>
        <td><%= link_to 'Show', switch %></td>
        <td><%= link_to 'Edit', edit_switch_path(switch) %></td>
        <td><%= link_to 'Destroy', switch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Switch', new_switch_path %>

app/views/switches/new.html.erb
<h1>New Switch</h1>

<%= render 'form', switch: @switch %>

<%= link_to 'Back', switches_path %>

app/views/switches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @switch.name %>
</p>

<p>
  <strong>Local ip:</strong>
  <%= @switch.local_ip %>
</p>

<p>
  <strong>User:</strong>
  <%= @switch.user %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @switch.pass %>
</p>

<%= link_to 'Edit', edit_switch_path(@switch) %> |
<%= link_to 'Back', switches_path %>